# -*- coding: utf-8 -*-
"""
提示词模块

包含所有 Agent 使用的提示词模板
"""

# RAG 提示词
from yoloapp.prompt.rag_prompts import (
    RAG_SYSTEM_PROMPT,
    RAG_QA_TEMPLATE,
    DETECTION_ANALYSIS_TEMPLATE,
    KNOWLEDGE_RETRIEVAL_PROMPT,
    NO_RELEVANT_INFO_RESPONSE,
    PARTIAL_INFO_RESPONSE_TEMPLATE,
)

# 响应生成提示词
from yoloapp.prompt.response_prompts import (
    CHAT_SYSTEM_PROMPT,
    GREETING_RESPONSE,
    GOODBYE_RESPONSE,
    CLARIFICATION_TEMPLATE,
    ERROR_RESPONSE,
    NO_IMAGE_RESPONSE,
    DETECTION_RESULT_TEMPLATE,
    DISEASE_FEATURE_TEMPLATE,
    TREATMENT_TEMPLATE,
    KNOWLEDGE_RESPONSE_TEMPLATE,
)

# 上下文管理提示词
from yoloapp.prompt.context_prompts import (
    CONTEXT_SYSTEM_PROMPT,
    CONTEXT_COMPRESSION_TEMPLATE,
    CONTEXT_PREFERENCE_ANALYSIS_TEMPLATE,
    CONTEXT_MERGE_TEMPLATE,
    CONTEXT_SKIP_TEMPLATE,
    CONTEXT_EXTRACTION_TEMPLATE,
)

# 记忆管理提示词
from yoloapp.prompt.memory_prompts import (
    MEMORY_SYSTEM_PROMPT,
    MEMORY_SUMMARY_TEMPLATE,
    MEMORY_COMPRESSION_TEMPLATE,
)

# 验证提示词
from yoloapp.prompt.validation_prompts import (
    INPUT_VALIDATION_SYSTEM_PROMPT,
    INPUT_VALIDATION_TEMPLATE,
    RESULT_VALIDATION_SYSTEM_PROMPT,
    RESULT_VALIDATION_TEMPLATE,
    CLARIFICATION_TEMPLATES,
)

# 规划提示词
from yoloapp.prompt.planning import (
    PLANNING_SYSTEM_PROMPT,
    PLANNING_WITH_TOOLS_PROMPT,
    TOOL_SELECTION_PROMPT,
    NEXT_STEP_PROMPT,
)

# 水稻病害专业提示词
from yoloapp.prompt.rice_disease_prompts import (
    INTENT_RECOGNITION_PROMPT,
    INPUT_VALIDATION_PROMPT,
    RESULT_VALIDATION_PROMPT,
    RAG_RETRIEVAL_PROMPT,
    CONTEXT_MANAGEMENT_PROMPT,
)

__all__ = [
    # RAG
    "RAG_SYSTEM_PROMPT",
    "RAG_QA_TEMPLATE",
    "DETECTION_ANALYSIS_TEMPLATE",
    "KNOWLEDGE_RETRIEVAL_PROMPT",
    "NO_RELEVANT_INFO_RESPONSE",
    "PARTIAL_INFO_RESPONSE_TEMPLATE",
    # Response
    "CHAT_SYSTEM_PROMPT",
    "GREETING_RESPONSE",
    "GOODBYE_RESPONSE",
    "CLARIFICATION_TEMPLATE",
    "ERROR_RESPONSE",
    "NO_IMAGE_RESPONSE",
    "DETECTION_RESULT_TEMPLATE",
    "DISEASE_FEATURE_TEMPLATE",
    "TREATMENT_TEMPLATE",
    "KNOWLEDGE_RESPONSE_TEMPLATE",
    # Context
    "CONTEXT_SYSTEM_PROMPT",
    "CONTEXT_COMPRESSION_TEMPLATE",
    "CONTEXT_PREFERENCE_ANALYSIS_TEMPLATE",
    "CONTEXT_MERGE_TEMPLATE",
    "CONTEXT_SKIP_TEMPLATE",
    "CONTEXT_EXTRACTION_TEMPLATE",
    # Memory
    "MEMORY_SYSTEM_PROMPT",
    "MEMORY_SUMMARY_TEMPLATE",
    "MEMORY_COMPRESSION_TEMPLATE",
    # Validation
    "INPUT_VALIDATION_SYSTEM_PROMPT",
    "INPUT_VALIDATION_TEMPLATE",
    "RESULT_VALIDATION_SYSTEM_PROMPT",
    "RESULT_VALIDATION_TEMPLATE",
    "CLARIFICATION_TEMPLATES",
    # Planning
    "PLANNING_SYSTEM_PROMPT",
    "PLANNING_WITH_TOOLS_PROMPT",
    "TOOL_SELECTION_PROMPT",
    "NEXT_STEP_PROMPT",
    # Rice Disease
    "INTENT_RECOGNITION_PROMPT",
    "INPUT_VALIDATION_PROMPT",
    "RESULT_VALIDATION_PROMPT",
    "RAG_RETRIEVAL_PROMPT",
    "CONTEXT_MANAGEMENT_PROMPT",
]
